version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies (if any)
  build:
    commands:
      - echo Build phase not needed for static site
artifacts:
  files:
    - '**/*'
  base-directory: '.'